### ISSUE TITLE
C# naming convention 

### ISSUE THREAD

**Issue by Lukasb7000** [Lukasb7000/Code#4]
**Is your feature request related to a problem?**
I am frustrated with naming convention we should stick with [Microsoft](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) naming
 
**Describe the solution you'd like**
When trying to program i found that not all variables or methods follow the same naming convention 

**Describe alternatives you've considered**
My suggestion would be to review all code and try sticking with Microsoft Naming Convension

**Comment by dov11s** [comment]
Okey i will check it.

**Comment by dov11s** [comment]
Checked all model classes

**Comment by dov11s** [comment]
Fixed found issues
